### PR TITLE
Remove anaphora

### PR DESCRIPTION
**Pull request by SubordinalBlue**
Continuing on removing dependencies from `array-operations`, I propose to remove dependencies on `anaphora`.

So far, I've just:
1. Found all instances of calls to `anaphora`, and...
2. ...prefixed them with `anaphora:`and...
3. ...removed `:use :anaphora` from "package.lisp" and..
4. ...verified I found everything by rebuilding and running tests.

This is just a draft PR. The actual removal remains to be done.

p.s.
I am unsure, at the moment, about removing `alexandria` later on.
- On the one hand, it's another dependency that really isn't that necessary for the `array-operations` code base.
- On the other, `alexandria` is pretty common, maybe most Common Lispers wouldn't mind.

I'm curious, what's your opinion?

### CODE REVIEW

**Comment by bendudson** [comment]
Thanks for all this thorough going-through of the code. I haven't checked how much `array-operations` depends on `alexandria`, but `alexandria` does seem to be very widely used. I'd rather use it than re-implement parts of it, unless the uses really are small or unnecessary.  I haven't been using Common Lisp for long though, so don't really have a good idea of the community's taste in these things.

**Comment by SubordinalBlue** [comment]
OK. I'll sit on that till after I finish removing the `anaphora` stuff.

I also haven't been using CL for long. (Well, I used it in some AI courses way back in the early 90's).

I appreciate this chance to contribute to a public CL project. It's helping me learn git better too. Thanks for taking my patches. 👍

**Comment by bendudson** [comment]
I'm not sure, but I think Travis is not testing this PR because it is marked "Draft" so can't be merged. This page (https://docs.travis-ci.com/user/pull-requests/) says Travis only tests PRs when they can be merged.

**Comment by SubordinalBlue** [comment]
As of just two days ago, Draft PRs are a new thing:

https://github.blog/2019-02-14-introducing-draft-pull-requests/ <https://github.blog/2019-02-14-introducing-draft-pull-requests/>

**Comment by SubordinalBlue** [comment]
Sorry, I was to brief.

Draft PRs are a new thing, and aren't meant to be merged. Just discussed. (and maybe to provide self motivation to the Draft PR submitter).

For later, when I've added code to make the PR complete, GitHub gives me a button to convert in to a normal PR.

**Pull request closed without merging**
