### PR TITLE
Add AOPS:TURN

### LINKED ISSUE #33: Is there a function for rotating an array by 90/180/270 degrees?
Is there any kind of operator that I can use to destructively/nondestructively "rotate" a 2D array by 90/180/270 degrees? If not, would it be permissible to add one?

Example behavior that I am thinking of:

```lisp
;; 90 degrees
#2A((1 0 0)    #2A((3 2 1)
    (2 0 0)  →     (0 0 0)
    (3 0 0))       (0 0 0))

;; 180 degrees
#2A((1 0 0)    #2A((0 0 3)
    (2 0 0)  →     (0 0 2)
    (3 0 0))       (0 0 1))

;; 270 degrees
#2A((1 0 0)    #2A((0 0 0)
    (2 0 0)  →     (0 0 0)
    (3 0 0))       (1 2 3))
```

### PR DESCRIPTION
**Pull request by phoe**
Fixes #33 

```lisp
(defun turn (array nturns &optional (rank-1 0) (rank-2 1))
  "Turns an array by a specified number of clockwise 90° rotations. The axis of
rotation is specified by RANK-1 (defaulting to 0) and RANK-2 (defaulting to 1)."
  ...)

### CODE REVIEW

**Comment by Symbolics** [comment]
Is there a reason for using lists to 'flip'? For large arrays this might have efficiency issues.

**Comment by phoe** [comment]
`array-dimensions` and `array-index-row-major` and `apply #'aref` all return or accept lists. If there are better solutions or ideas, I'll gladly implement them.

**Comment by Symbolics** [comment]
I can't think of any better ideas at the moment; perhaps a case of me optimizing too early, since I normally deal only with matrices (#2A ...), sometimes very large ones. All looks fine.

**Comment by phoe** [comment]
In theory, it should be possible to allocate a temporary list once and then mutate it on every iteration; that would reduce GC pressure by allocating less temporary lists for every element of the array, but would also require modifications to both introduced functions and would negatively impact code clarity.

**Comment by phoe** [comment]
Optimization is done - now there are fewer allocated lists in total and all per-element allocation is additionally DX.

**Comment by Symbolics** [comment]
Looks good. If Ben's happy to merge, this looks ready to go.

**Comment by phoe** [comment]
Beep boop.

**Comment by bendudson** [comment]
Thanks very much @phoe and @Symbolics ! Particular thanks for all the nice test cases. Sorry for the delay, been a bit distracted. Happy new year!

**Comment by phoe** [comment]
Thanks! Happy new year to you as well.

**Pull request merged**
