### PR TITLE
Regularized file names

### PR DESCRIPTION
**Pull request by SubordinalBlue**
This PR regularizes the source file names:

```
creation        -> creating
indexing        -> (no change)
reductions      -> reducing
stack           -> stacking
displacement    -> displacing
transformations -> transforming
utilities       -> (no change; also nice that it stands out from the rest, I think)
```

And also renames "general.lisp" to "generic.lisp"; IMO, that is more accurate.

Cheers.

[ Travis just came back with a fail, so I'll make this a draft PR until I fix it. ]

### CODE REVIEW

**Comment by SubordinalBlue** [comment]
After this, I am also thinking we might _add_ these files:

- "matrices.lisp" for the matrix-specific functions that are now in "general"/"generic".
- "mapping.lisp" for several existing functions that aren't named that way, but really are mappings.

**Comment by SubordinalBlue** [comment]
Found my goof. Had my coffee, too.

Travis is OK now.

Making this a real PR.

**Comment by bendudson** [comment]
Thanks! I agree this does make sense. Also glad that Travis is happy again and you've had your morning coffee :) 
Actually Travis is seldom happy, but this seems to be a problem with `closer-mop` and CLISP. This dependency seems to be coming from `optima`. I think it's only used in `stack` but might be a pain to remove. What do you think?

**Comment by SubordinalBlue** [comment]
I’ve been meaning to look at both CLISP and removing optima... that’d be great if one takes care of the other.

**Pull request merged**
